name: CI/CD

on:
  push:
    branches: [ master, Katende ]
  pull_request:
    branches: [ master, Katende ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build
    - name: Run tests
      run: npm test
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: build/

  deploy_to_staging:
    needs: build_and_test
    if: github.ref == 'refs/heads/Katende'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Download build artifacts
      uses: actions/download-artifact@v2
      with:
        name: build
        path: build/
    - name: Deploy to Heroku Staging
      uses: akhileshns/heroku-deploy@v3.12.14
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: ${{secrets.HEROKU_STAGING_APP_NAME}}
        heroku_email: ${{secrets.HEROKU_EMAIL}}
        appdir: "."
        procfile: "web: npm start"
        justlogin: true
    - name: Run smoke tests
      run: |
        # Add smoke tests here
        echo "Running smoke tests..."

  deploy_to_production:
    needs: [build_and_test, deploy_to_staging]
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Download build artifacts
      uses: actions/download-artifact@v2
      with:
        name: build
        path: build/
    - name: Deploy to Heroku Production
      uses: akhileshns/heroku-deploy@v3.12.14
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: ${{secrets.HEROKU_PRODUCTION_APP_NAME}}
        heroku_email: ${{secrets.HEROKU_EMAIL}}
        appdir: "."
        procfile: "web: npm start"
        justlogin: true
    - name: Run post-deployment tests
      run: |
        # Add post-deployment tests here
        echo "Running post-deployment tests..."
    - name: Rollback on failure
      if: failure()
      run: |
        heroku rollback ${{secrets.HEROKU_PRODUCTION_APP_NAME}}
      env:
        HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}

  monitor_production:
    needs: deploy_to_production
    runs-on: ubuntu-latest
    steps:
    - name: Check application health
      run: |
        # Add health check logic here
        echo "Checking application health..."
    - name: Rollback if health check fails
      if: failure()
      run: |
        heroku rollback ${{secrets.HEROKU_PRODUCTION_APP_NAME}}
      env:
        HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}