name: CI/CD

on:
  push:
    branches: [ master, Katende ]
  pull_request:
    branches: [ master, Katende ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'
    - name: Install dependencies
      run: npm install
    - name: Run tests
      run: npm test

  deploy-staging:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/Katende'
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'
    - name: Install dependencies
      run: npm install
    - name: Install Expo CLI
      run: npm install -g expo-cli
    - name: Build for Web
      run: npx expo export:web
    - name: Deploy to Heroku (Staging)
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP_NAME: "half-a-man-staging"
      run: |
        git config user.email "katendechris5@gmail.com"
        git config user.name "GitHub Actions"
        git add -f web-build
        git commit -m "Add build for Heroku deployment"
        git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:master --force
        
  deploy-production:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'
    - name: Install dependencies
      run: npm install
    - name: Install Expo CLI
      run: npm install -g expo-cli
    - name: Build for Web
      run: npx expo export:web
    - name: Deploy to Heroku (Production)
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP_NAME: "half-a-man-production"
      run: |
        git config user.email "github-actions@example.com"
        git config user.name "GitHub Actions"
        git add -f web-build
        git commit -m "Add build for Heroku deployment"
        git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:master --force