name: CI/CD

on:
  push:
    branches: [ master, Katende ]
  pull_request:
    branches: [ master, Katende ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'
    - name: Clear npm cache
      run: npm cache clean --force
    - name: Install dependencies
      run: npm install --legacy-peer-deps
    - name: Install dev dependencies
      run: npm install --only=dev
    - name: Run tests
      run: npm test
    - name: Output npm logs if failure
      if: failure()
      run: cat /home/runner/.npm/_logs/*-debug.log || true

  deploy-staging:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/Katende'
    
    steps:
    - uses: actions/checkout@v2
    - name: Install Expo CLI
      run: npm install -g expo-cli
    - name: Install dependencies
      run: npm install --legacy-peer-deps
    - name: Build for Web
      run: npx expo export:web
    - uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "half-a-man-staging"
        heroku_email: ${{secrets.HEROKU_EMAIL}}
        
  deploy-production:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    
    steps:
    - uses: actions/checkout@v2
    - name: Install Expo CLI
      run: npm install -g expo-cli
    - name: Install dependencies
      run: npm install --legacy-peer-deps
    - name: Build for Web
      run: npx expo export:web
    - uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "half-a-man-production"
        heroku_email: ${{secrets.HEROKU_EMAIL}}