name: CI/CD

on:
  push:
    branches: [ master, Katende ]
  pull_request:
    branches: [ master, Katende ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    - name: Install dependencies
      run: npm install
    - name: Build
      run: npm run build
    - name: Run tests
      run: npm test

  deploy_to_staging:
    needs: build_and_test
    if: github.ref == 'refs/heads/Katende'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    - name: Install dependencies and build
      run: |
        npm install
        npm ci
        npm run build
    - name: Deploy to Heroku Staging
      uses: akhileshns/heroku-deploy@v3.12.14
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: ${{secrets.HEROKU_STAGING_APP_NAME}}
        heroku_email: ${{secrets.HEROKU_EMAIL}}
        appdir: "web-build"
        procfile: "web: npm run heroku-start"
        justlogin: true

  deploy_to_production:
    needs: build_and_test
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    - name: Install dependencies and build
      run: |
        npm install
        npm run build
    - name: Deploy to Heroku Production
      uses: akhileshns/heroku-deploy@v3.12.14
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: ${{secrets.HEROKU_PRODUCTION_APP_NAME}}
        heroku_email: ${{secrets.HEROKU_EMAIL}}
        appdir: "web-build"
        procfile: "web: npm run heroku-start"
        justlogin: true