name: CI/CD

on:
  push:
    branches: [ master, Katende ]
  pull_request:
    branches: [ master, Katende ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'  # Updated to a more recent Node.js version
    - name: Debug - List files
      run: ls -la
    - name: Debug - Show package.json content
      run: cat package.json
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build
    - name: Test
      run: npm test
    - name: Output npm logs if failure
      if: failure()
      run: cat /home/runner/.npm/_logs/*-debug.log

  deploy-staging:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/Katende'
    
    steps:
    - uses: actions/checkout@v2
    - uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "half-a-man-staging"
        heroku_email: ${{secrets.HEROKU_EMAIL}}
        
  deploy-production:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    
    steps:
    - uses: actions/checkout@v2
    - uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "half-a-man-production"
        heroku_email: ${{secrets.HEROKU_EMAIL}}